### ISSUE TITLE
Possible freeze on first use

### ISSUE THREAD

**Issue by fwenzel** [fwenzel/copy-url#15]
> "One quirk is that the first time I use it after starting firefox it freezes firefox for something like 10 seconds. After that it works fine. Any ideas about how to fix this? If it's any help I'm using firefox 47.0.1 under Debian 8."

https://addons.mozilla.org/en-US/firefox/addon/copy-url-252534/reviews/808546/reply

**Comment by fwenzel** [comment]
Possible that it has something to do with the age of the add-ons SDK that I bundled this with. Will have to update that and see if the problem persists.

**Comment by fwenzel** [comment]
I released version 1.4.1 with the latest `jpm` framework and I cannot reproduce this. I think this is probably rightly fixed now. Please reopen with steps to reproduce if needed.

**Comment by jschultz** [comment]
Still happens I'm afraid, just as before. I don't think I am able to re-open the issue.

**Comment by fwenzel** [comment]
Thank you I just reopened. Not sure why you can't, maybe that's a setting I can change. Anyway. What version of Firefox do you use now? And did you make sure it's the latest version of the add-on? I can try on a clean version of Debian.

**Comment by jschultz** [comment]
Thanks for your attention. I just got back from an extended trip away from my office so finally might be able to help you investigate. I have the problem on two computers - both debian, one currently running Firefox ESR 45.0.1, the other Firefox 48.0. I'm happy (when I can find the time) to investigate further using a clean Debian VM. Let me know...

**Comment by fwenzel** [comment]
I would certainly appreciate it if there was any way to narrow this down further -- this is so weird. If there's anything in the error console perhaps. I am still not convinced it is caused by my extension itself, it might well be in the Mozilla framework, but either way I obviously would rather have my extension not block your browser as you open it up...!
